include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    todo: ignore

linter:
  rules:
    - prefer_final_locals
    - prefer_const_constructors
    - avoid_print
    - unawaited_futures
